# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? testing-aimee-front-end-001
  : build:
      target: development
    image: testing-aimee-front-end-001-development
    container_name: testing-aimee-front-end-001-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
